/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/Contact.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { Html, useGLTF, OrthographicCamera } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import ComposePlus from "../Icons/ComposePlus";
import { toast } from "react-toastify";
export function Contact({ onLoad }) {
  const { nodes, materials } = useGLTF("models/Contact3.glb");
  const modelRef = useRef();
  const letherChairRef = useRef();
  const penRef = useRef();
  const notebookRef = useRef();
  const formRef = useRef();
  const mapRef = useRef();
  const emailBtnRef = useRef();
  const [isHovered, setIsHovered] = useState(false);
  const [defaultRotation, setDefaultRotation] = useState({ x: 0.2, y: -0.8 });
  const [getQuoteActive, setGetQuoteActive] = useState(false);
  const getQuote = document.querySelector(".point-0");
  const socialMedia = document.querySelector(".point-1");
  const map = document.querySelector(".point-2");
  const emailContact = document.querySelector(".point-3");
  const telephone = document.querySelector(".point-4");
  const contactMap = document.querySelector("#contact-map");
  const getQuoteForm = document.querySelector("#get-quote-form");

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [contact, setContact] = useState("");
  const [budget, setBudget] = useState("");
  const [message, setMessage] = useState("");
  const [submitted, setSubmitted] = useState(false);

  async function handleSubmit(e) {
    e.preventDefault();
    if (!name || !email || !contact || !budget || !message) {
      toast.error("Please fill in all the details.");
      return;
    }

    try {
      let formData = new FormData();
      formData.append("name", name);
      formData.append("email", email);
      formData.append("contact", contact);
      formData.append("budget", budget);
      formData.append("message", message);

      // Convert FormData to a plain object
      let formObject = {};
      formData.forEach((value, key) => {
        formObject[key] = value;
      });

      // Convert the object to a JSON string
      let jsonData = JSON.stringify(formObject);

      toast.success("Thanks for contacting us");
      setSubmitted(true);
      setTimeout(() => {
        setName("");
        setEmail("");
        setContact("");
        setBudget("");
        setMessage("");
        setSubmitted(false);
      }, 2000);
      const response = await axios.post(
        "http://localhost:3000/send-mail",
        jsonData,
        {
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  }

  useFrame((state) => {
    if (modelRef.current && !getQuoteActive) {
      if (isHovered) {
        const { x, y } = state.mouse;
        const rotationIntensity = 0.1;
        const targetY = defaultRotation.y + x * rotationIntensity;
        const targetX = defaultRotation.x + y * rotationIntensity * 0.5;
        gsap.to(document.querySelector("#social-links"), {
          y: `${-y}rem`,
          x: `${-x * x}rem`,
        });
        modelRef.current.rotation.y +=
          (targetY - modelRef.current.rotation.y) * 0.1;
        modelRef.current.rotation.x +=
          (targetX - modelRef.current.rotation.x) * 0.1;
      } else {
        modelRef.current.rotation.y +=
          (defaultRotation.y - modelRef.current.rotation.y) * 0.1;
        modelRef.current.rotation.x +=
          (defaultRotation.x - modelRef.current.rotation.x) * 0.1;
      }
    }
  });

  useEffect(() => {
    const triggerEffect = (event) => {
      if (event.data === "triggerEffect") {
        showDots();
        gsap.to(modelRef.current.rotation, { x: 0.2, y: -0.8, z: 0 });
        gsap.to(modelRef.current.position, { x: 0.3, y: -1, z: 13.6 });
        setDefaultRotation({ x: 0.2, y: -0.8 });
        gsap.to(emailBtnRef.current, { scale: 0, duration: 0.2 });
        setGetQuoteActive(false);
        gsap.to(mapRef.current, {
          opacity: 0,
          duration: 0.4,
        });
        gsap.to(formRef.current, {
          opacity: 0,
          duration: 0.4,
        });
        // socialLinksContainer.style.display = "none";
        gsap.to(penRef.current.position, {
          x: 0,
          duration: 0.4,
          ease: "power1.out",
        });
        gsap.to(notebookRef.current.rotation, {
          y: 0,
          duration: 0.4,
          ease: "power1.out",
        });
      }
    };

    window.addEventListener("message", triggerEffect);
  }, []);
  useEffect(() => {
    onLoad();
  }, [onLoad]);

  const handleQuote = () => {
    setGetQuoteActive(true);
    const timeline = gsap.timeline();
    gsap.to(modelRef.current.rotation, {
      y: -Math.PI / 2,
      x: 1.5,
      duration: 0.5,
      ease: "power1.out",
    });
    timeline.to(modelRef.current.position, {
      z: 27,
      x: 0.1,
      y: -1,
      duration: 2,
      delay: 0.2,
    });
    gsap.to(letherChairRef.current.position, {
      x: -2.719,
      duration: 1,
      delay: 1,
      ease: "power1.out",
    });
    timeline.to(notebookRef.current.rotation, {
      y: 0.1,
      duration: 0.4,
      ease: "power1.out",
    });
    gsap.to(formRef.current, {
      opacity: 1,
      zIndex: 999,
      duration: 0.4,
      ease: "power1.out",
      delay: 3,
    });

    timeline.to(penRef.current.position, {
      x: 0.1,
      duration: 0.4,
      ease: "power1.out",
    });
    timeline.to(getQuoteForm, {
      opacity: 1,
      zIndex: 999,
      duration: 0.4,
      delay: 0.2,
    });
    setDefaultRotation({ x: 1.5, y: -Math.PI / 2 });
    vanishDots();
  };
  const handleMap = () => {
    setGetQuoteActive(true);
    const timeline = gsap.timeline();
    timeline.to(modelRef.current.rotation, {
      x: Math.PI / 2,
      y: -Math.PI / 2,
      duration: 1,
    });
    gsap.to(modelRef.current.position, { x: 1.4, y: 1.6, z: 24, duration: 1 });
    setDefaultRotation({ x: Math.PI / 2, y: -Math.PI / 2 });
    timeline.to(contactMap, {
      opacity: 1,
      zIndex: 999,
    });
    timeline.to(mapRef.current, {
      opacity: 1,
      duration: 0.4,
    });
    vanishDots();
  };
  const handleEmail = () => {
    setGetQuoteActive(true);
    const timeline1 = gsap.timeline();
    const timeline2 = gsap.timeline();
    timeline2.to(modelRef.current.position, { x: -1, y: 0, z: 20 });
    timeline2.to(modelRef.current.position, { x: -1, y: -0.3, z: 28 });
    timeline1.to(modelRef.current.rotation, { x: 0.2, y: -Math.PI / 2 });
    timeline1.to(modelRef.current.rotation, { y: -Math.PI / 2.9 });
    timeline2.to(emailBtnRef.current, { scale: 1, delay: 0.1 });
    setDefaultRotation({ x: 0.2, y: -Math.PI / 2.9 });
    vanishDots();
  };

  const handleSocial = () => {
    gsap.to(modelRef.current.rotation, {
      y: -Math.PI / 2.1,
      x: -0.01,
      duration: 1,
      ease: "power1.out",
    });
    gsap.to(modelRef.current.position, {
      z: 24,
      y: -1,
      x: 2,
      duration: 1,
      delay: 0.1,
    });

    vanishDots();
    setDefaultRotation({ x: -0.01, y: -Math.PI / 2.1 });
  };
  const handleTelephone = () => {
    const timeline = gsap.timeline();
    gsap.to(modelRef.current.position, { x: -1, y: -0.6, z: 29 });
    timeline.to(modelRef.current.rotation, {
      y: 0,
      x: 0.1,
      duration: 1,
      ease: "power1.out",
    });
    vanishDots();
    setDefaultRotation({ x: 0.1, y: 0 });
  };
  const vanishDots = () => {
    const elements = [getQuote, socialMedia, map, emailContact, telephone];
    elements.forEach((element) => {
      gsap.to(element, { scale: 0, duration: 0.5, ease: "power1.out" });
    });
  };
  const showDots = () => {
    gsap.to([".point"], { scale: 1, duration: 0.5 });
  };

  return (
    <group
      dispose={null}
      position={[0.3, -1, 13.6]}
      rotation={[0.2, -0.8, 0]}
      ref={modelRef}
      onPointerOver={() => {
        setIsHovered(true);
      }}
      onPointerOut={() => setIsHovered(false)}
    >
      <group position={[-3.261, 0.018, -3.292]}>
        <mesh
          geometry={nodes.curtain.geometry}
          material={materials["3"]}
          position={[4.407, 1.772, 0.216]}
          scale={[0.978, 1, 1]}
        />
        <mesh
          geometry={nodes.HANGER.geometry}
          material={materials["Material.009"]}
          position={[3.261, -0.018, 3.292]}
        />
        <mesh
          geometry={nodes.sheer.geometry}
          material={materials["3"]}
          position={[1.057, 1.681, 0.212]}
          scale={[0.886, 1, 1]}
        />
      </group>
      <group
        position={[-1.622, 0.837, -0.584]}
        rotation={[0, 1.518, 0]}
        scale={2.48}
      >
        <Html position={[0, 0.1, 0]}>
          <div className="point point-0 ping visible p-2">
            <div className="label " id="get-quote" onClick={handleQuote}></div>
            <div className="text opacity-0 text-nowrap">Get Quote</div>
          </div>
        </Html>

        <Html
          as="div"
          ref={formRef}
          position={[0, 0, 0]}
          // rotation-z={0.07}
          transform
          rotation-x={-Math.PI / 2}
          rotation-z={0}
          wrapperClass="get-quote-form"
          distanceFactor={0.25}
        >
          <form
            action="#"
            onSubmit={(e) => {
              handleSubmit(e);
            }}
          >
            <div>
              <label htmlFor="name">Name:</label>
              <input
                type="text"
                name="name"
                id="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </div>
            <div>
              <label htmlFor="email">Email:</label>
              <input
                type="email"
                name="email"
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <div>
              <label htmlFor="phnumber">Contact:</label>
              <input
                type="number"
                name="phnumber"
                id="phnumber"
                value={contact}
                onChange={(e) => setContact(e.target.value)}
              />
            </div>
            <div>
              <label htmlFor="budget">Budget:</label>
              <input
                type="number"
                name="budget"
                id="budget"
                value={budget}
                onChange={(e) => setBudget(e.target.value)}
              />
            </div>
            <div className="flex-col">
              <label htmlFor="comment">Message:</label>
              <textarea
                name="comment"
                id="comment"
                className="resize-none"
                rows={3}
                value={message}
                onChange={(e) => setMessage(e.target.value)}
              ></textarea>
            </div>
            <div className="flex justify-center">
              <button
                type="submit"
                id="contact-submit"
                className="w-20 h-10 flex items-center justify-center"
              >
                {submitted ? (
                  <Lottie
                    options={lottieDefaultOptions}
                    height={40}
                    width={40}
                  />
                ) : (
                  <span>Submit</span>
                )}
              </button>
            </div>
          </form>
        </Html>

        <Html position={[-1.2, 0.6, 0]}>
          <div className="point point-1 visible" onClick={handleSocial}>
            <div className="label" id="social-media"></div>
            <div className="text text-nowrap opacity-0">Social Media</div>
          </div>
        </Html>
        <mesh
          geometry={nodes.NOTE.geometry}
          material={materials["1"]}
          position={[-0.001, 0, -0.003]}
          ref={notebookRef}
        />
        <mesh
          geometry={nodes.pen.geometry}
          material={materials["1"]}
          position={[0.1, 0.02, 0.003]}
          ref={penRef}
        />
      </group>
      <group position={[0.968, 0.617, 0.839]} scale={1.372}>
        <Html position={[0, 0.1, 0]}>
          <div className="point point-2 ping visible p-2" onClick={handleMap}>
            <div className="label " id="map"></div>
            <div className="text opacity-0 text-nowrap">Map</div>
          </div>
        </Html>
        <Html
          position={[-0.01, 0, -0.03]}
          className="w-[499px] h-[499px]"
          transform
          rotation-x={-Math.PI / 2}
          distanceFactor={0.8}
          rotation-z={Math.PI / 2}
          wrapperClass="three-element"
          ref={mapRef}
        >
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d242117.70906496613!2d73.69815007997965!3d18.52487061413015!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bf2e67461101%3A0x828d43bf9d9ee343!2sPune%2C%20Maharashtra!5e0!3m2!1sen!2sin!4v1723526811933!5m2!1sen!2sin"
            width="100%"
            height="100%"
            style={{ border: 0 }}
            allowFullScreen=""
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
          ></iframe>
        </Html>
        <mesh
          geometry={nodes.BASE_AND_BUILD.geometry}
          material={materials["1"]}
          position={[-0.675, -0.01, -0.924]}
          scale={0.082}
        />
      </group>
      <OrthographicCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        position={[15.878, 8.748, 16.015]}
        rotation={[-0.429, 0.739, 0.293]}
      />
      <mesh geometry={nodes.FLOOR.geometry} material={materials["1"]} />
      <mesh geometry={nodes.LEFT_WALL.geometry} material={materials["1"]} />
      <mesh geometry={nodes.RIGHT_WALL.geometry} material={materials["1"]} />
      <mesh geometry={nodes.WOOD_PANEL.geometry} material={materials["1"]} />
      <mesh geometry={nodes.WOOD_PANEL001.geometry} material={materials["1"]} />
      <mesh geometry={nodes.Cube.geometry} material={materials["1"]} />
      <mesh geometry={nodes.LOCATION.geometry} material={materials["1"]} />
      <mesh geometry={nodes.FlowerPot.geometry} material={materials["2"]} />
      <group position={[-6, 1.2, 0]}>
        <Html
          position={[2.7, 0.36, 1.45]}
          transform
          // rotation-x={Math.PI / 2}
          rotation-y={Math.PI / 2}
          distanceFactor={3}
        >
          <ul className="flex items-center justify-center">
            <li className="w-[40px] h-[40px] mx-2">
              <a
                href="https://www.facebook.com"
                target="_blank"
                className="w-full h-full text-center block"
              ></a>
            </li>
            <li className="w-[40px] h-[40px] mx-2">
              <a
                href="https://www.instagram.com"
                target="_blank"
                className="w-full h-full text-center block"
              ></a>
            </li>
            <li className="w-[40px] h-[40px] mx-2">
              <a
                href="https://www.linkedin.com"
                target="_blank"
                className="w-full h-full text-center block"
              ></a>
            </li>
          </ul>
        </Html>
        <mesh
          geometry={nodes.Circle.geometry}
          position={[6, -1.2, 0]}
          material={materials["2"]}
        />
        <mesh
          geometry={nodes.Circle001.geometry}
          position={[6, -1.2, 0]}
          material={materials["2"]}
        />
        <mesh
          geometry={nodes.Circle002.geometry}
          position={[6, -1.2, 0]}
          material={materials["2"]}
        />
      </group>
      <mesh
        geometry={nodes.Folder_documents001.geometry}
        material={materials["1"]}
      />
      <group>
        <Html position={[0, 1, -2]}>
          <div className="point point-3 visible" onClick={handleEmail}>
            <div className="label" id="email-contact"></div>
            <div className="text text-nowrap opacity-0">Email</div>
          </div>
        </Html>

        <mesh geometry={nodes.Laptop.geometry} material={materials["4"]}>
          <Html
            ref={emailBtnRef}
            position={[-1, 0.78, -2.11]}
            rotation-y={1}
            transform
            distanceFactor={0.8}
            style={{ scale: 0 }}
          >
            <button
              className="px-4 py-2 shadow-lg bg-[#edecd2] rounded-full font-bold font-uber-move flex items-center"
              style={{ boxShadow: "0px 2px 5px black" }}
            >
              <ComposePlus />
              <a href="mailto:ayushr16060@gmail.com">Compose</a>
            </button>
          </Html>
        </mesh>
      </group>
      <mesh geometry={nodes.TABLE.geometry} material={materials["1"]} />
      <mesh geometry={nodes.TABLE_2.geometry} material={materials["1"]} />
      <mesh
        geometry={nodes.base.geometry}
        material={materials["3"]}
        position={[-2.419, 0.066, -0.504]}
        rotation={[Math.PI, -1.56, Math.PI]}
        ref={letherChairRef}
      />
      <mesh
        geometry={nodes.LIGHTMAP.geometry}
        material={materials["1"]}
        position={[-3.26, 2.003, -0.831]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.533}
      />
      <mesh
        geometry={nodes.Chair_Fabric_Parts001.geometry}
        material={materials["3"]}
        position={[0.867, 0.051, -2.323]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={1.161}
      />
      <group position={[1.668, 0.832, -1.776]}>
        <Html position={[0, 0.2, 0]}>
          <div className="point point-4 visible" onClick={handleTelephone}>
            <div className="label" id="tele-phone"></div>
            <div className="text opacity-0 text-nowrap">TelePhone</div>
          </div>
        </Html>
        <Html position={[0, 0.2, -1.5]} transform distanceFactor={1}>
          <div id="telephone-number">
            <h1 className="text-3xl font-sketch italic">
              <a href="tel:+919049616278" className="text-nowrap">
                +91-9049616278
              </a>
            </h1>
          </div>
        </Html>
        <mesh
          geometry={nodes.Body.geometry}
          material={materials["2"]}
          // position={[1.668, 0.832, -1.776]}
          scale={1.165}
        />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials["1"]} />
      <mesh geometry={nodes.Plane001_1.geometry} material={materials.GLASS} />
    </group>
  );
}

useGLTF.preload("models/Contact3.glb");
