/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/Contact.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import gsap from "gsap";
import * as THREE from "three";
import { OrbitControls } from "@react-three/drei";

export function ContactMobile(props) {
  const { nodes, materials } = useGLTF("models/Contact3.glb");
  const modelRef = useRef();
  const letherChairRef = useRef();
  const penRef = useRef();
  const notebookRef = useRef();

  const [isHovered, setIsHovered] = useState(false);
  const [defaultRotation, setDefaultRotation] = useState({ x: 0.2, y: -0.8 });
  const [defaultPosition, setDefaultPosition] = useState({ x: -0.1, y: -2.7 });
  const [getQuoteActive, setGetQuoteActive] = useState(false);
  const getQuote = document.querySelector(".point-0");
  const socialMedia = document.querySelector(".point-1");
  const map = document.querySelector(".point-2");
  const emailContact = document.querySelector(".point-3");
  const telephone = document.querySelector(".point-4");
  const socialLinksContainer = document.querySelector("#social-links");
  const emailComposeBtn = document.querySelector("#email-compose-btn");
  const telephoneNumber = document.querySelector("#telephone-number");
  const contactMap = document.querySelector("#contact-map");
  const getQuoteForm = document.querySelector("#get-quote-form");
  const { camera } = useThree();

  // Handle mouse movement when hovering over the model
  useFrame((state) => {
    if (modelRef.current && !getQuoteActive) {
      if (isHovered) {
        const { x, y } = state.mouse;
        const rotationIntensity = 0.1; // How much the model rotates based on cursor

        // Calculate the rotation offset based on mouse position
        const targetY = defaultRotation.y + x * rotationIntensity;
        const targetX = defaultRotation.x + y * rotationIntensity * 0.5;

        gsap.to(document.querySelector("#social-links"), {
          y: `${-y}rem`,
          x: `${-x * x}rem`,
        });

        // Smoothly interpolate towards the target rotation
        modelRef.current.rotation.y +=
          (targetY - modelRef.current.rotation.y) * 0.1;
        modelRef.current.rotation.x +=
          (targetX - modelRef.current.rotation.x) * 0.1;
        gsap.to(socialMedia, { x: -340, y: -20, duration: 0.5 });
        gsap.to(map, { x: -205, y: 70, duration: 0.5 });
        gsap.to(emailContact, { x: -140, y: 40, duration: 0.5 });
        gsap.to(telephone, { x: -100, y: 40, duration: 0.5 });
      } else {
        // Rotate back to the default position when mouse leaves
        modelRef.current.rotation.y +=
          (defaultRotation.y - modelRef.current.rotation.y) * 0.1;
        modelRef.current.rotation.x +=
          (defaultRotation.x - modelRef.current.rotation.x) * 0.1;
      }
    }
  });
  useEffect(() => {
    // Apply initial transforms using GSAP
    gsap.to(getQuote, { x: -248, y: 20, duration: 0.5 });
    gsap.to(socialMedia, { x: -340, y: -20, duration: 0.5 });
    gsap.to(map, { x: -205, y: 70, duration: 0.5 });
    gsap.to(emailContact, { x: -140, y: 40, duration: 0.5 });
    gsap.to(telephone, { x: -100, y: 40, duration: 0.5 });

    // Event listeners
    const eventHandlers = [
      { element: getQuote, handler: handleQuote },
      { element: socialMedia, handler: handleSocial },
      { element: map, handler: handleMap },
      { element: emailContact, handler: handleEmail },
      { element: telephone, handler: handleTelephone },
    ];

    eventHandlers.forEach(({ element, handler }) =>
      element.addEventListener("click", () => {
        vanishDots();
        handler();
      })
    );

    window.addEventListener("click", (e) => {
      const outsideClick =
        !document.querySelector("canvas").contains(e.target) &&
        !document
          .querySelector("#contact-canvas-components")
          .contains(e.target) &&
        eventHandlers.every(({ element }) => !element.contains(e.target));

      if (outsideClick) {
        gsap.to(modelRef.current.rotation, { x: 0.2, y: -0.8, z: 0 });
        gsap.to(modelRef.current.position, { x: -0.1, y: -2.7, z: 0 });
        setDefaultRotation({ x: 0.2, y: -0.8 });
        showDots();
        setGetQuoteActive(false);
        socialLinksContainer.style.display = "none";
        gsap.to(emailComposeBtn, { scale: 0, duration: 0 });
        gsap.to(telephoneNumber, { opacity: 0, zIndex: -10, duration: 0 });
        gsap.to(contactMap, {
          opacity: 0,
          zIndex: -10,
        });
        gsap.to(penRef.current.position, {
          // position={[0, 0.02, 0.003]}
          x: 0,
          duration: 0.4,
          ease: "power1.out",
        });
        gsap.to(notebookRef.current.rotation, {
          // position={[0, 0.02, 0.003]}
          y: 0,
          duration: 0.4,
          ease: "power1.out",
        });
        gsap.to(getQuoteForm, {
          opacity: 0,
          zIndex: -10,
          duration: 0,
        });
      }
    });
  }, []);
  const vanishDots = () => {
    const elements = [getQuote, socialMedia, map, emailContact, telephone];
    elements.forEach((element) => {
      gsap.to(element, { scale: 0, duration: 0.5, ease: "power1.out" });
    });
  };
  const showDots = () => {
    const elements = [getQuote, socialMedia, map, emailContact, telephone];
    elements.forEach((element) => {
      gsap.to(element, { scale: 1, duration: 0.5, ease: "power1.out" });
    });
  };

  const handleQuote = () => {
    // camera.position.lerp({ x: 1, y: 1, z: 1.5 }, 0.1);
    // camera.lookAt(1, 1, 1);
    setGetQuoteActive(true);
    const timeline = gsap.timeline();
    gsap.to(modelRef.current.rotation, {
      y: -Math.PI / 2,
      x: 1.5,
      duration: 0.5,
      ease: "power1.out",
    });
    timeline.to(modelRef.current.position, {
      z: 27.1,
      x: 0.2,
      y: -1.7,
      duration: 2,
      delay: 0.2,
    });
    gsap.to(letherChairRef.current.position, {
      x: -2.719,
      duration: 1,
      delay: 1,
      ease: "power1.out",
    });
    timeline.to(notebookRef.current.rotation, {
      // position={[0, 0.02, 0.003]}
      y: 0.1,
      duration: 0.4,
      ease: "power1.out",
    });
    timeline.to(penRef.current.position, {
      // position={[0, 0.02, 0.003]}
      x: 0.1,
      duration: 0.4,
      ease: "power1.out",
    });
    timeline.to(getQuoteForm, {
      opacity: 1,
      zIndex: 999,
      duration: 0.4,
      delay: 0.2,
    });
    setDefaultRotation({ x: 1.5, y: -Math.PI / 2 });
  };

  const handleSocial = () => {
    socialLinksContainer.style.display = "block";
    gsap.to(modelRef.current.rotation, {
      y: -Math.PI / 2.1,
      x: -0.01,
      duration: 1,
      ease: "power1.out",
    });
    gsap.to(modelRef.current.position, {
      z: 22,
      y: -2.6,
      x: 2,
      duration: 1,
      delay: 0.1,
    });
    setDefaultRotation({ x: -0.01, y: -Math.PI / 2.1 });
  };

  const handleMap = () => {
    setGetQuoteActive(true);
    const timeline = gsap.timeline();
    timeline.to(modelRef.current.rotation, {
      x: Math.PI / 2,
      y: -Math.PI / 2,
      duration: 1,
    });
    gsap.to(modelRef.current.position, { x: 1.4, y: 0.8, z: 22, duration: 1 });
    setDefaultRotation({ x: Math.PI / 2, y: -Math.PI / 2 });
    timeline.to(contactMap, {
      opacity: 1,
      zIndex: 999,
    });
  };

  const handleEmail = () => {
    const timeline1 = gsap.timeline();
    const timeline2 = gsap.timeline();
    timeline2.to(modelRef.current.position, { x: -0.9, y: -2, z: 20 });
    timeline2.to(modelRef.current.position, { x: -0.9, y: -1, z: 28 });
    timeline1.to(modelRef.current.rotation, { x: 0.2, y: -Math.PI / 2 });
    timeline1.to(modelRef.current.rotation, { y: -Math.PI / 2.9 });
    timeline2.to(emailComposeBtn, { scale: 1, delay: 0.1 });
    setDefaultRotation({ x: 0.2, y: -Math.PI / 2.9 });
  };

  const handleTelephone = () => {
    setGetQuoteActive(true);
    const timeline = gsap.timeline();
    gsap.to(modelRef.current.position, { x: -0.8, y: -1.5, z: 28 });
    timeline.to(modelRef.current.rotation, {
      y: 0,
      x: 0.1,
      duration: 1,
      ease: "power1.out",
    });
    timeline.to(telephoneNumber, {
      opacity: 1,
      zIndex: 999,
      delay: 0.5,
    });
    setDefaultRotation({ x: 0.1, y: 0 });
  };
  function SampleMethod() {
    console.log("Clicked");
  }

  return (
    <group
      {...props}
      dispose={null}
      position={[-0.1, -2.7, 0]}
      rotation={[0.2, -0.8, 0]}
      scale={1}
      ref={modelRef}
      onPointerOver={() => {
        setIsHovered(true);
      }}
      onPointerOut={() => setIsHovered(false)}
    >
      <group position={[-3.261, 0.018, -3.292]}>
        <mesh
          geometry={nodes.curtain.geometry}
          material={materials["3"]}
          position={[4.407, 1.772, 0.216]}
          scale={[0.978, 1, 1]}
        />
        <mesh
          geometry={nodes.HANGER.geometry}
          material={materials["Material.009"]}
          position={[3.261, -0.018, 3.292]}
        />
        <mesh
          geometry={nodes.sheer.geometry}
          material={materials["3"]}
          position={[1.057, 1.681, 0.212]}
          scale={[0.886, 1, 1]}
        />
      </group>
      <group
        position={[-1.622, 0.837, -0.584]}
        rotation={[0, 1.518, 0]}
        scale={2.48}
      >
        <mesh
          geometry={nodes.NOTE.geometry}
          material={materials["1"]}
          position={[-0.001, 0, -0.003]}
          onClick={SampleMethod}
        />
        <mesh
          ref={penRef}
          geometry={nodes.pen.geometry}
          material={materials["1"]}
          position={[0, 0.02, 0.003]}
        />
      </group>
      <group position={[0.968, 0.617, 0.839]} scale={1.372}>
        <mesh
          geometry={nodes.BASE_AND_BUILD.geometry}
          material={materials["1"]}
          position={[-0.675, -0.01, -0.924]}
          scale={0.082}
        />
      </group>
      {/* <OrthographicCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        position={[15.878, 8.748, 16.015]}
        rotation={[-0.429, 0.739, 0.293]}
      /> */}
      <mesh geometry={nodes.FLOOR.geometry} material={materials["1"]} />
      <mesh geometry={nodes.LEFT_WALL.geometry} material={materials["1"]} />
      <mesh geometry={nodes.RIGHT_WALL.geometry} material={materials["1"]} />
      <mesh geometry={nodes.WOOD_PANEL.geometry} material={materials["1"]} />
      <mesh geometry={nodes.WOOD_PANEL001.geometry} material={materials["1"]} />
      <mesh geometry={nodes.Cube.geometry} material={materials["1"]} />
      <mesh geometry={nodes.LOCATION.geometry} material={materials["1"]} />
      <mesh geometry={nodes.FlowerPot.geometry} material={materials["2"]} />
      <mesh geometry={nodes.Circle.geometry} material={materials["2"]} />
      <mesh geometry={nodes.Circle001.geometry} material={materials["2"]} />
      <mesh geometry={nodes.Circle002.geometry} material={materials["2"]} />
      <mesh
        geometry={nodes.Folder_documents001.geometry}
        material={materials["1"]}
      />
      <mesh geometry={nodes.Laptop.geometry} material={materials["4"]} />
      <mesh geometry={nodes.TABLE.geometry} material={materials["1"]} />
      <mesh geometry={nodes.TABLE_2.geometry} material={materials["1"]} />
      <mesh
        geometry={nodes.base.geometry}
        material={materials["3"]}
        position={[-2.419, 0.066, -0.504]}
        rotation={[Math.PI, -1.56, Math.PI]}
        ref={letherChairRef}
      />
      <mesh
        geometry={nodes.LIGHTMAP.geometry}
        material={materials["1"]}
        position={[-3.26, 2.003, -0.831]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.533}
      />
      <mesh
        geometry={nodes.Chair_Fabric_Parts001.geometry}
        material={materials["3"]}
        position={[0.867, 0.051, -2.323]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={1.161}
      />
      <mesh
        geometry={nodes.Body.geometry}
        material={materials["2"]}
        position={[1.668, 0.832, -1.776]}
        scale={1.165}
      />
      <mesh geometry={nodes.Plane001.geometry} material={materials["1"]} />
      <mesh geometry={nodes.Plane001_1.geometry} material={materials.GLASS} />
    </group>
  );
}

useGLTF.preload("models/Contact.glb");
