/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/CoreServicesModel.glb 
*/

import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from "react";
import { useFrame, useGraph, useThree } from "@react-three/fiber";
import {
  useGLTF,
  OrthographicCamera,
  useAnimations,
  Html,
  OrbitControls,
} from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import gsap from "gsap";
import * as THREE from "three";

const CoreServicesModel = forwardRef((props, ref) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/CoreServicesModel.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  const [Hover, setHover] = useState(false);
  const defaultCameraButton = document.querySelector("#default-camera-button");
  const [defaultPos, setDefaultPos] = useState({
    x: -20.837,
    y: 6.528,
    z: 10.32,
  });
  const [defaultRot, setDefaultRot] = useState({
    x: -0.4569635742958074,
    y: -1.075626922382597,
    z: -0.4083045728810875,
  });
  const position_x = -20.837;
  const position_y = 6.528;
  const position_z = 10.32;
  const rotate_x = -0.4569635742958074;
  const rotate_y = -1.075626922382597;
  const rotate_z = -0.4083045728810875;
  const { camera, controls } = useThree();
  const section1Ref = useRef();

  // To handle room click
  const handleRoomClick = (e) => {
    if (defaultCameraButton) {
      gsap.to(defaultCameraButton, {
        opacity: 1,
        scale: 1,
      });
    }
    if (e.target.id == "section-1" && section1Ref.current) {
      defaultPos.x = 10;
      defaultPos.y = 6;
      defaultPos.z = 2;
      defaultRot.x = 0;
      defaultRot.y = Math.PI / 18;
      defaultRot.z = 0;
    }
    if (e.target.id == "section-2") {
      defaultPos.x = 4;
      defaultPos.y = 10;
      defaultPos.z = 8;
      defaultRot.x = 0;
      defaultRot.y = rotate_y - 0.4;
      defaultRot.z = 0;
    }
    if (e.target.id == "section-3") {
      defaultPos.x = 7;
      defaultPos.y = 10;
      defaultPos.z = 0.5;
      defaultRot.x = 0;
      defaultRot.y = rotate_y;
      defaultRot.z = 0;
    }
    if (e.target.id == "section-4") {
      defaultPos.x = -5;
      defaultPos.y = 3;
      defaultPos.z = -10;
      defaultRot.x = 0;
      defaultRot.y = rotate_y - 0.5;
      defaultRot.z = 0;
    }
    gsap.to(camera.position, {
      x: defaultPos.x,
      y: defaultPos.y,
      z: defaultPos.z,
    });

    gsap.to(camera.rotation, {
      x: defaultRot.x,
      y: defaultRot.y,
      z: defaultRot.z,
    });
  };

  useImperativeHandle(ref, () => ({
    setCamera: defaultCamera,
  }));
  const defaultCamera = () => {
    setDefaultRot({ x: rotate_x, y: rotate_y, z: rotate_z });
    gsap.to(camera.position, {
      x: position_x,
      y: position_y,
      z: position_z,
    });
    gsap.to(camera.rotation, {
      x: rotate_x,
      y: rotate_y,
      z: rotate_z,
    });
    gsap.to(defaultCameraButton, {
      opacity: 0,
      scale: 0,
    });
    console.log("Core Serivces Child");
  };

  // Frames for moving camera on cursor move
  useFrame((state) => {
    if (Hover) {
      const { x, y } = state.mouse;
      const rotationIntensity = 0.05;
      const targetY = defaultRot.y + x * rotationIntensity;
      const targetX = defaultRot.x + (y * rotationIntensity) / 2;
      camera.rotation.y += (targetY - camera.rotation.y) * 0.1;
      camera.rotation.x += (targetX - camera.rotation.x) * 0.1;
    }
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      // rotation={[0, 0, 0]}
      // position={[-1, 0, 16.6]}
      rotation={[0, 0, 0]}
      onPointerOver={() => setHover(true)}
      onPointerOut={() => setHover(false)}
    >
      {/* <OrbitControls onChange={(e) => handleChange(e)} /> */}
      <group name="Scene">
        <group
          name="Area"
          position={[-9.349, 16.562, -38.478]}
          rotation={[-2.06, -0.79, -0.965]}
          scale={117.852}
        />
        <group
          name="Area001"
          position={[29.039, 28.052, 20.636]}
          rotation={[-0.68, -0.155, 1.125]}
          scale={117.852}
        />
        <group name="Turbulence" position={[-12.516, 0.077, -29.974]} />
        <group
          name="Rigged_Car"
          position={[14.03, 0.077, 18.748]}
          rotation={[0, Math.PI / 2, 0]}
          ref={section1Ref}
        >
          <primitive object={nodes["DEF-Body"]} />
          <primitive object={nodes["DEF-WheelFtL"]} />
          <primitive object={nodes["DEF-WheelFtR"]} />
          <primitive object={nodes["DEF-WheelBkL"]} />
          <primitive object={nodes["DEF-WheelBkR"]} />
          <primitive object={nodes.Root} />
          <primitive object={nodes["MCH-WheelrotationFtL"]} />
          <primitive object={nodes["MCH-WheelrotationFtR"]} />
          <primitive object={nodes["MCH-WheelrotationBkL"]} />
          <primitive object={nodes["MCH-WheelrotationBkR"]} />
          <primitive object={nodes["MCH-Steeringrotation"]} />
        </group>
        <group
          name="Rigged_Car001"
          position={[14.03, 0.077, 22.633]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <primitive object={nodes["DEF-Body_1"]} />
          <primitive object={nodes["DEF-WheelFtL_1"]} />
          <primitive object={nodes["DEF-WheelFtR_1"]} />
          <primitive object={nodes["DEF-WheelBkL_1"]} />
          <primitive object={nodes["DEF-WheelBkR_1"]} />
          <primitive object={nodes.Root_1} />
          <primitive object={nodes["MCH-WheelrotationFtL_1"]} />
          <primitive object={nodes["MCH-WheelrotationFtR_1"]} />
          <primitive object={nodes["MCH-WheelrotationBkL_1"]} />
          <primitive object={nodes["MCH-WheelrotationBkR_1"]} />
          <primitive object={nodes["MCH-Steeringrotation_1"]} />
        </group>
        <group name="CMT_Line" />
        <group
          name="Low_Poly_Pine_Evergreen_Tree"
          position={[25.295, 0, 16.227]}
          scale={1.216}
        >
          <mesh
            name="leaves"
            geometry={nodes.leaves.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk"
            geometry={nodes.Trunk.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree001"
          position={[30.034, 0, 16.227]}
          scale={0.855}
        >
          <mesh
            name="leaves001"
            geometry={nodes.leaves001.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk001"
            geometry={nodes.Trunk001.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree002"
          position={[28.119, 0, 22.654]}
          scale={1.088}
        >
          <mesh
            name="leaves002"
            geometry={nodes.leaves002.geometry}
            material={materials.tree}
            rotation={[-Math.PI, 0.972, -Math.PI]}
          />
          <mesh
            name="Trunk002"
            geometry={nodes.Trunk002.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree003"
          position={[33.837, 0, 22.654]}
          scale={1.002}
        >
          <mesh
            name="leaves003"
            geometry={nodes.leaves003.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk003"
            geometry={nodes.Trunk003.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree004"
          position={[33.837, 0, 11.62]}
          scale={1.207}
        >
          <mesh
            name="leaves004"
            geometry={nodes.leaves004.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk004"
            geometry={nodes.Trunk004.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree005"
          position={[34.702, 0, 17.559]}
          rotation={[-Math.PI, 0.397, -Math.PI]}
          scale={1.365}
        >
          <mesh
            name="leaves005"
            geometry={nodes.leaves005.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk005"
            geometry={nodes.Trunk005.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree006"
          position={[27.652, 0, -2.172]}
          scale={1.216}
        >
          <mesh
            name="leaves006"
            geometry={nodes.leaves006.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk006"
            geometry={nodes.Trunk006.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree007"
          position={[26.87, 0, -25.703]}
          scale={0.855}
        >
          <mesh
            name="leaves007"
            geometry={nodes.leaves007.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk007"
            geometry={nodes.Trunk007.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree008"
          position={[30.476, 0, 4.255]}
          scale={1.088}
        >
          <mesh
            name="leaves008"
            geometry={nodes.leaves008.geometry}
            material={materials.tree}
            rotation={[-Math.PI, 0.972, -Math.PI]}
          />
          <mesh
            name="Trunk008"
            geometry={nodes.Trunk008.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree009"
          position={[36.194, 0, -26.616]}
          scale={1.002}
        >
          <mesh
            name="leaves009"
            geometry={nodes.leaves009.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk009"
            geometry={nodes.Trunk009.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree010"
          position={[36.194, 0, -6.779]}
          scale={1.207}
        >
          <mesh
            name="leaves010"
            geometry={nodes.leaves010.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk010"
            geometry={nodes.Trunk010.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree011"
          position={[21.781, 0, 22.653]}
          rotation={[-Math.PI, 0.397, -Math.PI]}
          scale={0.926}
        >
          <mesh
            name="leaves011"
            geometry={nodes.leaves011.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk011"
            geometry={nodes.Trunk011.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree012"
          position={[36.832, 0, -17.619]}
          rotation={[Math.PI, -0.382, Math.PI]}
          scale={1.216}
        >
          <mesh
            name="leaves012"
            geometry={nodes.leaves012.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk012"
            geometry={nodes.Trunk012.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree013"
          position={[32.434, 0, -15.855]}
          rotation={[Math.PI, -0.382, Math.PI]}
          scale={0.855}
        >
          <mesh
            name="leaves013"
            geometry={nodes.leaves013.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk013"
            geometry={nodes.Trunk013.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree014"
          position={[31.819, 0, -22.533]}
          rotation={[Math.PI, -0.382, Math.PI]}
          scale={1.088}
        >
          <mesh
            name="leaves014"
            geometry={nodes.leaves014.geometry}
            material={materials.tree}
            rotation={[-Math.PI, 0.972, -Math.PI]}
          />
          <mesh
            name="Trunk014"
            geometry={nodes.Trunk014.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree015"
          position={[26.512, 0, -20.404]}
          rotation={[Math.PI, -0.382, Math.PI]}
          scale={1.002}
        >
          <mesh
            name="leaves015"
            geometry={nodes.leaves015.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk015"
            geometry={nodes.Trunk015.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree016"
          position={[30.62, 0, -10.164]}
          rotation={[Math.PI, -0.382, Math.PI]}
          scale={1.207}
        >
          <mesh
            name="leaves016"
            geometry={nodes.leaves016.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk016"
            geometry={nodes.Trunk016.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree017"
          position={[27.606, 0, -15.353]}
          rotation={[0, -0.015, 0]}
          scale={1.365}
        >
          <mesh
            name="leaves017"
            geometry={nodes.leaves017.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk017"
            geometry={nodes.Trunk017.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree018"
          position={[32.49, 0, 0.046]}
          rotation={[0, -0.267, 0]}
          scale={1.216}
        >
          <mesh
            name="leaves018"
            geometry={nodes.leaves018.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk018"
            geometry={nodes.Trunk018.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree019"
          position={[37.061, 0, 1.295]}
          rotation={[0, -0.267, 0]}
          scale={0.855}
        >
          <mesh
            name="leaves019"
            geometry={nodes.leaves019.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk019"
            geometry={nodes.Trunk019.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree020"
          position={[33.52, 0, 6.99]}
          rotation={[0, -0.267, 0]}
          scale={1.088}
        >
          <mesh
            name="leaves020"
            geometry={nodes.leaves020.geometry}
            material={materials.tree}
            rotation={[-Math.PI, 0.972, -Math.PI]}
          />
          <mesh
            name="Trunk020"
            geometry={nodes.Trunk020.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree021"
          position={[39.035, 0, 8.497]}
          rotation={[0, -0.267, 0]}
          scale={1.002}
        >
          <mesh
            name="leaves021"
            geometry={nodes.leaves021.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk021"
            geometry={nodes.Trunk021.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree022"
          position={[41.943, 0, -2.147]}
          rotation={[0, -0.267, 0]}
          scale={1.207}
        >
          <mesh
            name="leaves022"
            geometry={nodes.leaves022.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk022"
            geometry={nodes.Trunk022.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree023"
          position={[41.212, 0, 3.81]}
          rotation={[-Math.PI, 0.664, -Math.PI]}
          scale={1.365}
        >
          <mesh
            name="leaves023"
            geometry={nodes.leaves023.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk023"
            geometry={nodes.Trunk023.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree024"
          position={[-0.545, 0, -30.605]}
          rotation={[0, -1.521, 0]}
          scale={1.002}
        >
          <mesh
            name="leaves024"
            geometry={nodes.leaves024.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk024"
            geometry={nodes.Trunk024.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree025"
          position={[10.475, 0, -31.154]}
          rotation={[0, -1.521, 0]}
          scale={1.207}
        >
          <mesh
            name="leaves025"
            geometry={nodes.leaves025.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk025"
            geometry={nodes.Trunk025.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree026"
          position={[4.587, 0, -29.994]}
          rotation={[0, 1.224, 0]}
          scale={1.365}
        >
          <mesh
            name="leaves026"
            geometry={nodes.leaves026.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk026"
            geometry={nodes.Trunk026.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree027"
          position={[14.874, 0, -26.926]}
          rotation={[0, 0.972, 0]}
          scale={1.216}
        >
          <mesh
            name="leaves027"
            geometry={nodes.leaves027.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk027"
            geometry={nodes.Trunk027.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree028"
          position={[17.543, 0, -30.842]}
          rotation={[0, 0.972, 0]}
          scale={0.855}
        >
          <mesh
            name="leaves028"
            geometry={nodes.leaves028.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk028"
            geometry={nodes.Trunk028.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree029"
          position={[21.775, 0, -25.639]}
          rotation={[0, 0.972, 0]}
          scale={1.088}
        >
          <mesh
            name="leaves029"
            geometry={nodes.leaves029.geometry}
            material={materials.tree}
            rotation={[-Math.PI, 0.972, -Math.PI]}
          />
          <mesh
            name="Trunk029"
            geometry={nodes.Trunk029.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree030"
          position={[24.996, 0, -30.363]}
          rotation={[0, 0.972, 0]}
          scale={1.002}
        >
          <mesh
            name="leaves030"
            geometry={nodes.leaves030.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk030"
            geometry={nodes.Trunk030.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree031"
          position={[15.879, 0, -36.578]}
          rotation={[0, 0.972, 0]}
          scale={1.207}
        >
          <mesh
            name="leaves031"
            geometry={nodes.leaves031.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk031"
            geometry={nodes.Trunk031.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree032"
          position={[21.273, 0, -33.948]}
          rotation={[Math.PI, -0.575, Math.PI]}
          scale={1.365}
        >
          <mesh
            name="leaves032"
            geometry={nodes.leaves032.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk032"
            geometry={nodes.Trunk032.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree033"
          position={[1.082, 0, -22.016]}
          rotation={[0, 0.972, 0]}
          scale={1.216}
        >
          <mesh
            name="leaves033"
            geometry={nodes.leaves033.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk033"
            geometry={nodes.Trunk033.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree034"
          position={[3.752, 0, -25.931]}
          rotation={[0, 0.972, 0]}
          scale={0.855}
        >
          <mesh
            name="leaves034"
            geometry={nodes.leaves034.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk034"
            geometry={nodes.Trunk034.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree035"
          position={[7.983, 0, -20.728]}
          rotation={[0, 0.972, 0]}
          scale={1.088}
        >
          <mesh
            name="leaves035"
            geometry={nodes.leaves035.geometry}
            material={materials.tree}
            rotation={[-Math.PI, 0.972, -Math.PI]}
          />
          <mesh
            name="Trunk035"
            geometry={nodes.Trunk035.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree036"
          position={[11.204, 0, -25.452]}
          rotation={[0, 0.972, 0]}
          scale={1.002}
        >
          <mesh
            name="leaves036"
            geometry={nodes.leaves036.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk036"
            geometry={nodes.Trunk036.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Low_Poly_Pine_Evergreen_Tree037"
          position={[-2.317, 0, -25.66]}
          rotation={[0, 0.972, 0]}
          scale={1.207}
        >
          <mesh
            name="leaves037"
            geometry={nodes.leaves037.geometry}
            material={materials.tree}
          />
          <mesh
            name="Trunk037"
            geometry={nodes.Trunk037.geometry}
            material={materials.Bark}
          />
        </group>
        <group
          name="Beach_umbrella"
          position={[-3.207, 0, 13.194]}
          scale={1.126}
        >
          <group name="mount" position={[0, 2.656, 0]} />
          <group name="mount001" position={[0, 2.656, 0]} />
          <group name="mounts036" position={[0, 2.656, 0]} />
          <group name="plank" position={[0, 2.656, 0]} />
          <mesh
            name="base"
            geometry={nodes.base.geometry}
            material={materials["concrete (Dirty)"]}
          />
          <mesh
            name="base_cap"
            geometry={nodes.base_cap.geometry}
            material={materials.metals}
            position={[0, 0.125, 0]}
            rotation={[Math.PI, -1.554, Math.PI]}
          />
          <mesh
            name="main_fabric"
            geometry={nodes.main_fabric.geometry}
            material={materials.umbrella_fabric}
            position={[0, 2.581, 0]}
            rotation={[0, -1.568, 0]}
          />
          <mesh
            name="post"
            geometry={nodes.post.geometry}
            material={materials.umbrella_wood}
            position={[0, 2.295, 0]}
          />
          <mesh
            name="top_fabric"
            geometry={nodes.top_fabric.geometry}
            material={materials.umbrella_fabric}
            position={[0, 2.559, 0]}
            rotation={[Math.PI, -1.554, Math.PI]}
          />
        </group>
        <group
          name="Beach_umbrella001"
          position={[-11.345, 0, 13.194]}
          scale={1.126}
        >
          <group name="mount002" position={[0, 2.656, 0]} />
          <group name="mount003" position={[0, 2.656, 0]} />
          <group name="mounts001" position={[0, 2.656, 0]} />
          <group name="plank001" position={[0, 2.656, 0]} />
          <mesh
            name="base001"
            geometry={nodes.base001.geometry}
            material={materials["concrete (Dirty)"]}
          />
          <mesh
            name="base_cap001"
            geometry={nodes.base_cap001.geometry}
            material={materials.metals}
            position={[0, 0.125, 0]}
            rotation={[Math.PI, -1.554, Math.PI]}
          />
          <mesh
            name="main_fabric001"
            geometry={nodes.main_fabric001.geometry}
            material={materials.umbrella_fabric}
            position={[0, 2.581, 0]}
            rotation={[0, -1.568, 0]}
          />
          <mesh
            name="post001"
            geometry={nodes.post001.geometry}
            material={materials.umbrella_wood}
            position={[0, 2.295, 0]}
          />
          <mesh
            name="top_fabric001"
            geometry={nodes.top_fabric001.geometry}
            material={materials.umbrella_fabric}
            position={[0, 2.559, 0]}
            rotation={[Math.PI, -1.554, Math.PI]}
          />
        </group>
        <group
          name="Tree_base"
          position={[-16.306, 0.077, -4.901]}
          scale={0.564}
        >
          <mesh
            name="Crown"
            geometry={nodes.Crown.geometry}
            material={materials.Crown}
            position={[-0.336, 9.525, -4.206]}
          />
          <mesh
            name="Trunk038"
            geometry={nodes.Trunk038.geometry}
            material={materials.Trunk}
          />
        </group>
        <group
          name="Tree_base001"
          position={[-15.668, 0.077, -20.483]}
          rotation={[Math.PI, -0.755, Math.PI]}
          scale={0.564}
        >
          <mesh
            name="Crown001"
            geometry={nodes.Crown001.geometry}
            material={materials.Crown}
            position={[-0.336, 9.525, -4.206]}
          />
          <mesh
            name="Trunk039"
            geometry={nodes.Trunk039.geometry}
            material={materials.Trunk}
          />
        </group>
        <group
          name="Tree_base002"
          position={[-8.903, 0.077, -12.489]}
          rotation={[0, -0.574, 0]}
          scale={0.564}
        >
          <mesh
            name="Crown002"
            geometry={nodes.Crown002.geometry}
            material={materials.Crown}
            position={[-0.336, 9.525, -4.206]}
          />
          <mesh
            name="Trunk040"
            geometry={nodes.Trunk040.geometry}
            material={materials.Trunk}
          />
        </group>
        <group name="BagaPie_Handrail" position={[0, -0.818, -4.543]} />
        {/* <OrthographicCamera
          name="Camera"
          makeDefault={true}
          // far={1000}
          // near={1}
          position={[0, 0, 0]}
          rotation={[0, 0, 0]}
          fov={50}
        /> */}
        <mesh
          name="10450_Rectangular_Grass_Patch_v1_iterations-2"
          geometry={
            nodes["10450_Rectangular_Grass_Patch_v1_iterations-2"].geometry
          }
          material={materials["10450_Rectangular_Grass_Patch_v1"]}
          position={[-12.272, -0.16, -15.971]}
          scale={[0.043, 0.043, 0.099]}
        />
        <group
          name="Cube008"
          position={[9.443, -0.3, -4.207]}
          scale={[30.33, 0.3, 30.33]}
        >
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Cube_1"
            geometry={nodes.Cube_1.geometry}
            material={materials["Procedural Grid material"]}
          />
        </group>
        <group
          name="Cube001"
          position={[4.545, 2, -8.625]}
          scale={[7.427, 2, 4.727]}
        >
          <Html>
            <div className="point point-0 ping visible p-2">
              <div
                className="label "
                id="section-4"
                onClick={(e) => handleRoomClick(e)}
              ></div>
              <div className="text opacity-0 text-nowrap">Section-4</div>
            </div>
          </Html>
          <mesh
            name="Cube007_1"
            geometry={nodes.Cube007_1.geometry}
            material={materials["Hunton  BLACK oak.001"]}
          />
          <mesh
            name="Cube007_2"
            geometry={nodes.Cube007_2.geometry}
            material={materials.wall}
          />
          <mesh
            name="Cube007_3"
            geometry={nodes.Cube007_3.geometry}
            material={materials.floor}
          />
          <mesh
            name="Cube007_4"
            geometry={nodes.Cube007_4.geometry}
            material={materials.floor}
          />
          <group name="Baga_Window7152401" position={[14.833, 8.837, -4.016]}>
            <mesh
              name="Plane001"
              geometry={nodes.Plane001.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane001_1"
              geometry={nodes.Plane001_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <group name="Baga_Window7905853" position={[14.833, 8.837, -4.016]}>
            <mesh
              name="Plane"
              geometry={nodes.Plane.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane_1"
              geometry={nodes.Plane_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <mesh
            name="Baga_Window_Bool4944385"
            geometry={nodes.Baga_Window_Bool4944385.geometry}
            material={materials.BagaPie_Glass}
            position={[14.833, 8.837, -4.016]}
          />
          <mesh
            name="Baga_Window_Bool5845556"
            geometry={nodes.Baga_Window_Bool5845556.geometry}
            material={materials.BagaPie_Glass}
            position={[14.833, 8.837, -4.016]}
          />
        </group>
        <group
          name="Cube002"
          position={[9.762, 6.1, -4.67]}
          rotation={[-Math.PI, 1.366, -Math.PI]}
          scale={[7.427, 2, 3.37]}
        >
          <Html position={[0, 0.1, 0]}>
            <div
              className="point point-0 ping visible"
              onClick={(e) => handleRoomClick(e)}
            >
              <div className="label" id="section-1"></div>
              <div className="text opacity-0 text-nowrap flex">Section 1</div>
            </div>
          </Html>
          <mesh
            name="Cube008_1"
            geometry={nodes.Cube008_1.geometry}
            material={materials["Hunton White oak"]}
          />
          <mesh
            name="Cube008_2"
            geometry={nodes.Cube008_2.geometry}
            material={materials["wall.004"]}
          />
          <mesh
            name="Cube008_3"
            geometry={nodes.Cube008_3.geometry}
            material={materials["floor.004"]}
          />
          <group name="Baga_Window2413041" position={[19.415, 4.1, 3.81]}>
            <mesh
              name="Plane012"
              geometry={nodes.Plane012.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane012_1"
              geometry={nodes.Plane012_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <mesh
            name="Baga_Window_Bool5184752"
            geometry={nodes.Baga_Window_Bool5184752.geometry}
            material={materials.BagaPie_Glass}
            position={[19.415, 4.1, 3.81]}
          />
        </group>
        <group
          name="Cube003"
          position={[10.351, 6.1, 6.279]}
          rotation={[0, 0.213, 0]}
          scale={[5.044, 2, 3.37]}
        >
          <mesh
            name="Cube009_1"
            geometry={nodes.Cube009_1.geometry}
            material={materials["Hunton White oak"]}
          />
          <mesh
            name="Cube009_2"
            geometry={nodes.Cube009_2.geometry}
            material={materials["wall.002"]}
          />
          <mesh
            name="Cube009_3"
            geometry={nodes.Cube009_3.geometry}
            material={materials["floor.002"]}
          />
          <group name="Baga_Window1305977" position={[19.415, 4.1, 3.81]}>
            <mesh
              name="Plane013"
              geometry={nodes.Plane013.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane013_1"
              geometry={nodes.Plane013_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <group name="Baga_Window3792740" position={[6.949, 0, 7.72]}>
            <mesh
              name="Plane014"
              geometry={nodes.Plane014.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane014_1"
              geometry={nodes.Plane014_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <mesh
            name="Baga_Window_Bool5054303"
            geometry={nodes.Baga_Window_Bool5054303.geometry}
            material={materials.BagaPie_Glass}
            position={[6.949, 0, 7.72]}
          />
          <mesh
            name="Baga_Window_Bool5391082"
            geometry={nodes.Baga_Window_Bool5391082.geometry}
            material={materials.BagaPie_Glass}
            position={[19.415, 4.1, 3.81]}
          />
        </group>
        <group
          name="Cube004"
          position={[14.833, 10.2, -4.016]}
          rotation={[0, 0.268, 0]}
          scale={[5.044, 2, 3.37]}
        >
          <Html>
            <div className="point point-0 ping visible p-2">
              <div
                className="label "
                id="section-3"
                onClick={(e) => handleRoomClick(e)}
              ></div>
              <div className="text opacity-0 text-nowrap">Section 3</div>
            </div>
          </Html>
          <mesh
            name="Cube010_1"
            geometry={nodes.Cube010_1.geometry}
            material={materials["Hunton  BLACK oak.001"]}
          />
          <mesh
            name="Cube010_2"
            geometry={nodes.Cube010_2.geometry}
            material={materials["wall.005"]}
          />
          <mesh
            name="Cube010_3"
            geometry={nodes.Cube010_3.geometry}
            material={materials["floor.005"]}
          />
          <group name="Baga_Window484074" position={[6.949, 0, 7.72]}>
            <mesh
              name="Plane016"
              geometry={nodes.Plane016.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane016_1"
              geometry={nodes.Plane016_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <group name="Baga_Window8469794" position={[6.931, 9.601, 10.596]}>
            <mesh
              name="Plane018"
              geometry={nodes.Plane018.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane018_1"
              geometry={nodes.Plane018_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <mesh
            name="Baga_Window_Bool2324839"
            geometry={nodes.Baga_Window_Bool2324839.geometry}
            material={materials.BagaPie_Glass}
            position={[6.931, 9.601, 10.596]}
          />
          <mesh
            name="Baga_Window_Bool5617842"
            geometry={nodes.Baga_Window_Bool5617842.geometry}
            material={materials.BagaPie_Glass}
            position={[6.949, 0, 7.72]}
          />
        </group>
        <group
          name="Cube005"
          position={[8.474, 4.05, -7.81]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-14.769, -0.05, -7.085]}
        >
          <mesh
            name="Cube021_1"
            geometry={nodes.Cube021_1.geometry}
            material={materials["Hunton  BLACK oak.001"]}
          />
          <mesh
            name="Cube021_2"
            geometry={nodes.Cube021_2.geometry}
            material={materials["Hunton  BLACK oak.001"]}
          />
        </group>
        <mesh
          name="Cube006"
          geometry={nodes.Cube006.geometry}
          material={materials["Hunton White oak"]}
          position={[9.402, 8.15, -6.289]}
          rotation={[Math.PI, -0.219, Math.PI]}
          scale={[-5.141, -0.05, -8.07]}
        />
        <mesh
          name="Cube007"
          geometry={nodes.Cube007.geometry}
          material={materials["Hunton  BLACK oak.001"]}
          position={[14.833, 12.25, -4.016]}
          rotation={[0, 0.26, 0]}
          scale={[6.194, 0.05, 3.971]}
        />
        <group
          name="Cube009"
          position={[10.38, 10.2, 6.339]}
          rotation={[Math.PI, -0.227, Math.PI]}
          scale={[5.044, 2, 3.37]}
        >
          <Html>
            <div className="point point-0 ping visible p-2">
              <div
                className="label "
                id="section-2"
                onClick={(e) => handleRoomClick(e)}
              ></div>
              <div className="text opacity-0 text-nowrap">Section 2</div>
            </div>
          </Html>
          <mesh
            name="Cube018"
            geometry={nodes.Cube018.geometry}
            material={materials["Hunton White oak"]}
          />
          <mesh
            name="Cube018_1"
            geometry={nodes.Cube018_1.geometry}
            material={materials["wall.003"]}
          />
          <mesh
            name="Cube018_2"
            geometry={nodes.Cube018_2.geometry}
            material={materials["floor.003"]}
          />
          <group name="Baga_Window6567765" position={[6.949, 0, 7.72]}>
            <mesh
              name="Plane015"
              geometry={nodes.Plane015.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane015_1"
              geometry={nodes.Plane015_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <group name="Baga_Window6632896" position={[6.931, 9.601, 10.596]}>
            <mesh
              name="Plane017"
              geometry={nodes.Plane017.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane017_1"
              geometry={nodes.Plane017_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <mesh
            name="Baga_Window_Bool2364094"
            geometry={nodes.Baga_Window_Bool2364094.geometry}
            material={materials.BagaPie_Glass}
            position={[6.949, 0, 7.72]}
          />
          <mesh
            name="Baga_Window_Bool9275346"
            geometry={nodes.Baga_Window_Bool9275346.geometry}
            material={materials.BagaPie_Glass}
            position={[6.931, 9.601, 10.596]}
          />
        </group>
        <mesh
          name="Cube010"
          geometry={nodes.Cube010.geometry}
          material={materials["Hunton White oak"]}
          position={[10.468, 12.25, 6.327]}
          rotation={[Math.PI, -0.219, Math.PI]}
          scale={[6.194, 0.05, 3.971]}
        />
        <group
          name="Cube012"
          position={[15.27, 2, 1.512]}
          rotation={[-Math.PI, 1.561, -Math.PI]}
          scale={[7.427, 2, 3.37]}
        >
          <mesh
            name="Cube002_1"
            geometry={nodes.Cube002_1.geometry}
            material={materials["Hunton  BLACK oak.001"]}
          />
          <mesh
            name="Cube002_2"
            geometry={nodes.Cube002_2.geometry}
            material={materials["wall.001"]}
          />
          <mesh
            name="Cube002_3"
            geometry={nodes.Cube002_3.geometry}
            material={materials["floor.001"]}
          />
          <group name="Baga_Window6421104" position={[15.23, 2, 1.512]}>
            <mesh
              name="Plane011"
              geometry={nodes.Plane011.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane011_1"
              geometry={nodes.Plane011_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <group name="Baga_Window7886078" position={[18.7, 0.035, 0.264]}>
            <mesh
              name="Plane010"
              geometry={nodes.Plane010.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane010_1"
              geometry={nodes.Plane010_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <group name="Baga_Window8691265" position={[18.7, 0.035, 0.264]}>
            <mesh
              name="Plane007"
              geometry={nodes.Plane007.geometry}
              material={materials.BagaPie_Glass}
            />
            <mesh
              name="Plane007_1"
              geometry={nodes.Plane007_1.geometry}
              material={materials.BagaPie_Window}
            />
          </group>
          <mesh
            name="Baga_Window_Bool150227"
            geometry={nodes.Baga_Window_Bool150227.geometry}
            material={materials.BagaPie_Glass}
            position={[18.7, 0.035, 0.264]}
          />
          <mesh
            name="Baga_Window_Bool604412"
            geometry={nodes.Baga_Window_Bool604412.geometry}
            material={materials.BagaPie_Glass}
            position={[15.27, 2, 1.512]}
          />
          <mesh
            name="Baga_Window_Bool9611872"
            geometry={nodes.Baga_Window_Bool9611872.geometry}
            material={materials.BagaPie_Glass}
            position={[18.7, 0.035, 0.264]}
          />
        </group>
        <mesh
          name="BagaPie_Column"
          geometry={nodes.BagaPie_Column.geometry}
          material={materials.dark}
          position={[6.949, 0, 10.038]}
          scale={[1, 2.066, 1]}
        />
        <mesh
          name="BagaPie_Column001"
          geometry={nodes.BagaPie_Column001.geometry}
          material={materials.dark}
          position={[5.242, 0, 4.2]}
          scale={[1, 2.066, 1]}
        />
        <mesh
          name="BagaPie_Column002"
          geometry={nodes.BagaPie_Column002.geometry}
          material={materials.dark}
          position={[20.311, 4.064, -2.36]}
          scale={[1, 2.079, 1]}
        />
        <mesh
          name="BagaPie_Column003"
          geometry={nodes.BagaPie_Column003.geometry}
          material={materials.dark}
          position={[18.604, 4.064, -8.198]}
          scale={[1, 2.079, 1]}
        />
        <mesh
          name="BagaPie_Fence"
          geometry={nodes.BagaPie_Fence.geometry}
          material={nodes.BagaPie_Fence.material}
          position={[-9.349, 0.033, -20.094]}
        />
        <mesh
          name="Plane006"
          geometry={nodes.Plane006.geometry}
          material={materials["spruce wood rough clean"]}
          position={[-1.706, 0.033, 13.238]}
          rotation={[Math.PI, -0.079, Math.PI]}
          scale={1.284}
        />
        <mesh
          name="Plane002"
          geometry={nodes.Plane002.geometry}
          material={materials["spruce wood rough clean"]}
          position={[-4.519, 0.033, 13.238]}
          rotation={[Math.PI, -0.079, Math.PI]}
          scale={1.284}
        />
        <mesh
          name="Plane003"
          geometry={nodes.Plane003.geometry}
          material={materials["spruce wood rough clean"]}
          position={[-9.719, 0.033, 13.238]}
          rotation={[Math.PI, -0.079, Math.PI]}
          scale={1.284}
        />
        <mesh
          name="Plane004"
          geometry={nodes.Plane004.geometry}
          material={materials["spruce wood rough clean"]}
          position={[-12.681, 0.033, 13.238]}
          rotation={[Math.PI, -0.079, Math.PI]}
          scale={1.284}
        />
        <mesh
          name="Cube022"
          geometry={nodes.Cube022.geometry}
          material={nodes.Cube022.material}
          position={[-12.551, 0.155, -1.96]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube024"
          geometry={nodes.Cube024.geometry}
          material={nodes.Cube024.material}
          position={[-12.512, 0.185, -3.919]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube026"
          geometry={nodes.Cube026.geometry}
          material={nodes.Cube026.material}
          position={[-12.403, 0.155, -5.478]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube027"
          geometry={nodes.Cube027.geometry}
          material={nodes.Cube027.material}
          position={[-12.546, 0.155, -7.229]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube028"
          geometry={nodes.Cube028.geometry}
          material={nodes.Cube028.material}
          position={[-12.668, 0.155, -8.744]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube029"
          geometry={nodes.Cube029.geometry}
          material={nodes.Cube029.material}
          position={[-12.768, 0.155, -10.284]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube030"
          geometry={nodes.Cube030.geometry}
          material={nodes.Cube030.material}
          position={[-12.697, 0.155, -11.773]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube031"
          geometry={nodes.Cube031.geometry}
          material={nodes.Cube031.material}
          position={[-12.835, 0.155, -13.439]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube032"
          geometry={nodes.Cube032.geometry}
          material={nodes.Cube032.material}
          position={[-13.331, 0.155, -15.042]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube033"
          geometry={nodes.Cube033.geometry}
          material={nodes.Cube033.material}
          position={[-13.335, 0.155, -16.497]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube034"
          geometry={nodes.Cube034.geometry}
          material={nodes.Cube034.material}
          position={[-13.062, 0.155, -17.84]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube025"
          geometry={nodes.Cube025.geometry}
          material={nodes.Cube025.material}
          position={[-12.54, 0.155, -19.441]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube035"
          geometry={nodes.Cube035.geometry}
          material={nodes.Cube035.material}
          position={[-12.122, 0.155, -20.973]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube036"
          geometry={nodes.Cube036.geometry}
          material={nodes.Cube036.material}
          position={[-11.739, 0.155, -22.4]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube037"
          geometry={nodes.Cube037.geometry}
          material={nodes.Cube037.material}
          position={[-11.217, 0.155, -23.862]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube038"
          geometry={nodes.Cube038.geometry}
          material={nodes.Cube038.material}
          position={[-11.568, 0.155, -25.416]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube039"
          geometry={nodes.Cube039.geometry}
          material={nodes.Cube039.material}
          position={[-11.919, 0.155, -26.87]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube040"
          geometry={nodes.Cube040.geometry}
          material={nodes.Cube040.material}
          position={[-12.169, 0.155, -28.323]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cube041"
          geometry={nodes.Cube041.geometry}
          material={nodes.Cube041.material}
          position={[-12.57, 0.155, -29.677]}
          scale={[0.542, 0.149, 0.542]}
        />
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.013"]}
          position={[-10.105, 0.201, -6.643]}
          scale={[0.058, 0.182, 0.058]}
        />
        <mesh
          name="Cylinder001"
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.013"]}
          position={[-10.105, 0.201, -12.177]}
          scale={[0.058, 0.182, 0.058]}
        />
        <mesh
          name="Cylinder002"
          geometry={nodes.Cylinder002.geometry}
          material={materials["Material.013"]}
          position={[-14.469, 0.225, -8.665]}
          scale={[0.058, 0.182, 0.058]}
        />
        <mesh
          name="Cylinder003"
          geometry={nodes.Cylinder003.geometry}
          material={materials["Material.013"]}
          position={[-14.469, 0.189, -22.411]}
          scale={[0.058, 0.182, 0.058]}
        />
        <mesh
          name="Cylinder004"
          geometry={nodes.Cylinder004.geometry}
          material={materials["Material.013"]}
          position={[-14.469, 0.225, -2.798]}
          scale={[0.058, 0.182, 0.058]}
        />
        <mesh
          name="Cylinder005"
          geometry={nodes.Cylinder005.geometry}
          material={materials["Material.013"]}
          position={[-9.223, 0.201, -21.499]}
          scale={[0.058, 0.182, 0.058]}
        />
        <mesh
          name="Cube021"
          geometry={nodes.Cube021.geometry}
          material={nodes.Cube021.material}
          position={[-17.256, 0.007, 21.345]}
          scale={[1.171, 0.089, 0.046]}
        />
        <mesh
          name="Cube023"
          geometry={nodes.Cube023.geometry}
          material={nodes.Cube023.material}
          position={[-10.982, 0.007, 21.345]}
          scale={[1.171, 0.089, 0.046]}
        />
        <mesh
          name="Cube042"
          geometry={nodes.Cube042.geometry}
          material={nodes.Cube042.material}
          position={[-3.543, 0.007, 21.345]}
          scale={[1.171, 0.089, 0.046]}
        />
        <mesh
          name="Cube043"
          geometry={nodes.Cube043.geometry}
          material={nodes.Cube043.material}
          position={[4.546, 0.007, 21.345]}
          scale={[1.171, 0.089, 0.046]}
        />
        <group
          name="light"
          position={[2.03, 0, 1.496]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder007"
            geometry={nodes.Cylinder007.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder007_1"
            geometry={nodes.Cylinder007_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light001"
          position={[2.03, 0, 4.662]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder008"
            geometry={nodes.Cylinder008.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder008_1"
            geometry={nodes.Cylinder008_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light002"
          position={[2.03, 0, 6.916]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder009"
            geometry={nodes.Cylinder009.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder009_1"
            geometry={nodes.Cylinder009_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light003"
          position={[2.03, 0, 9.607]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder010"
            geometry={nodes.Cylinder010.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder010_1"
            geometry={nodes.Cylinder010_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light004"
          position={[2.03, 0, 11.881]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder011"
            geometry={nodes.Cylinder011.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder011_1"
            geometry={nodes.Cylinder011_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light005"
          position={[-3.33, 0, 1.496]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder012"
            geometry={nodes.Cylinder012.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder012_1"
            geometry={nodes.Cylinder012_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light006"
          position={[-3.33, 0, 11.881]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder013"
            geometry={nodes.Cylinder013.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder013_1"
            geometry={nodes.Cylinder013_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light007"
          position={[-7.239, 0, 1.496]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder014"
            geometry={nodes.Cylinder014.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder014_1"
            geometry={nodes.Cylinder014_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light008"
          position={[-7.239, 0, 11.881]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder015"
            geometry={nodes.Cylinder015.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder015_1"
            geometry={nodes.Cylinder015_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light009"
          position={[-11.278, 0, 1.496]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder016"
            geometry={nodes.Cylinder016.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder016_1"
            geometry={nodes.Cylinder016_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light010"
          position={[-11.278, 0, 11.881]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder017"
            geometry={nodes.Cylinder017.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder017_1"
            geometry={nodes.Cylinder017_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light011"
          position={[-14.624, 0, 1.496]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder018"
            geometry={nodes.Cylinder018.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder018_1"
            geometry={nodes.Cylinder018_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light012"
          position={[-14.624, 0, 11.881]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder019"
            geometry={nodes.Cylinder019.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder019_1"
            geometry={nodes.Cylinder019_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light013"
          position={[-14.644, 0, 4.662]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder020"
            geometry={nodes.Cylinder020.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder020_1"
            geometry={nodes.Cylinder020_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light014"
          position={[-14.644, 0, 6.916]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder021"
            geometry={nodes.Cylinder021.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder021_1"
            geometry={nodes.Cylinder021_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light015"
          position={[-14.644, 0, 9.607]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder022"
            geometry={nodes.Cylinder022.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder022_1"
            geometry={nodes.Cylinder022_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light016"
          position={[2.03, 0, -1.699]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder023"
            geometry={nodes.Cylinder023.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder023_1"
            geometry={nodes.Cylinder023_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light017"
          position={[6.365, 0, -1.699]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder024"
            geometry={nodes.Cylinder024.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder024_1"
            geometry={nodes.Cylinder024_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light018"
          position={[-2.125, 0, -1.699]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder025"
            geometry={nodes.Cylinder025.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder025_1"
            geometry={nodes.Cylinder025_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light019"
          position={[-5.356, 0, -1.699]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder026"
            geometry={nodes.Cylinder026.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder026_1"
            geometry={nodes.Cylinder026_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light020"
          position={[-5.356, 0, -5.183]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder027"
            geometry={nodes.Cylinder027.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder027_1"
            geometry={nodes.Cylinder027_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light021"
          position={[-5.356, 0, -8.994]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder028"
            geometry={nodes.Cylinder028.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder028_1"
            geometry={nodes.Cylinder028_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light022"
          position={[-5.356, 0, -13.136]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder029"
            geometry={nodes.Cylinder029.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder029_1"
            geometry={nodes.Cylinder029_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light023"
          position={[-5.356, 0, -16.138]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder030"
            geometry={nodes.Cylinder030.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder030_1"
            geometry={nodes.Cylinder030_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light024"
          position={[8.255, 0, 0.941]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder068"
            geometry={nodes.Cylinder068.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder068_1"
            geometry={nodes.Cylinder068_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light025"
          position={[8.255, 0, 4.764]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder069"
            geometry={nodes.Cylinder069.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder069_1"
            geometry={nodes.Cylinder069_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light026"
          position={[8.255, 0, 8.99]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder070"
            geometry={nodes.Cylinder070.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder070_1"
            geometry={nodes.Cylinder070_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light027"
          position={[8.255, 0, 12.637]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder071"
            geometry={nodes.Cylinder071.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder071_1"
            geometry={nodes.Cylinder071_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light028"
          position={[11.743, 0, 12.913]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder072"
            geometry={nodes.Cylinder072.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder072_1"
            geometry={nodes.Cylinder072_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light029"
          position={[15.621, 0, 12.913]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder073"
            geometry={nodes.Cylinder073.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder073_1"
            geometry={nodes.Cylinder073_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light030"
          position={[21.296, 0, 12.913]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder074"
            geometry={nodes.Cylinder074.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder074_1"
            geometry={nodes.Cylinder074_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light031"
          position={[25.171, 0, 12.913]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder075"
            geometry={nodes.Cylinder075.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder075_1"
            geometry={nodes.Cylinder075_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light032"
          position={[25.171, 0, 9.728]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder076"
            geometry={nodes.Cylinder076.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder076_1"
            geometry={nodes.Cylinder076_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light033"
          position={[-3.334, 0, 17.07]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder077"
            geometry={nodes.Cylinder077.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder077_1"
            geometry={nodes.Cylinder077_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light034"
          position={[-8.694, 0, 17.07]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder078"
            geometry={nodes.Cylinder078.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder078_1"
            geometry={nodes.Cylinder078_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light035"
          position={[-12.602, 0, 17.07]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder079"
            geometry={nodes.Cylinder079.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder079_1"
            geometry={nodes.Cylinder079_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light036"
          position={[-16.642, 0, 17.07]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder080"
            geometry={nodes.Cylinder080.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder080_1"
            geometry={nodes.Cylinder080_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light037"
          position={[-19.988, 0, 17.07]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder081"
            geometry={nodes.Cylinder081.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder081_1"
            geometry={nodes.Cylinder081_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light040"
          position={[7.799, 0, 17.07]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder084"
            geometry={nodes.Cylinder084.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder084_1"
            geometry={nodes.Cylinder084_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light041"
          position={[3.76, 0, 17.07]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder085"
            geometry={nodes.Cylinder085.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder085_1"
            geometry={nodes.Cylinder085_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light042"
          position={[0.414, 0, 17.07]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder086"
            geometry={nodes.Cylinder086.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder086_1"
            geometry={nodes.Cylinder086_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light043"
          position={[17.068, 0, 25.456]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder087"
            geometry={nodes.Cylinder087.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder087_1"
            geometry={nodes.Cylinder087_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light044"
          position={[11.708, 0, 25.456]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder088"
            geometry={nodes.Cylinder088.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder088_1"
            geometry={nodes.Cylinder088_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light045"
          position={[7.799, 0, 25.456]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder089"
            geometry={nodes.Cylinder089.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder089_1"
            geometry={nodes.Cylinder089_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light046"
          position={[3.76, 0, 25.456]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder090"
            geometry={nodes.Cylinder090.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder090_1"
            geometry={nodes.Cylinder090_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light047"
          position={[0.414, 0, 25.456]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder091"
            geometry={nodes.Cylinder091.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder091_1"
            geometry={nodes.Cylinder091_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light038"
          position={[-3.334, 0, 25.371]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder092"
            geometry={nodes.Cylinder092.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder092_1"
            geometry={nodes.Cylinder092_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light039"
          position={[-8.694, 0, 25.371]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder093"
            geometry={nodes.Cylinder093.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder093_1"
            geometry={nodes.Cylinder093_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light048"
          position={[-12.602, 0, 25.371]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder094"
            geometry={nodes.Cylinder094.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder094_1"
            geometry={nodes.Cylinder094_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light049"
          position={[-16.642, 0, 25.371]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder095"
            geometry={nodes.Cylinder095.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder095_1"
            geometry={nodes.Cylinder095_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          name="light050"
          position={[-19.988, 0, 25.371]}
          scale={[0.043, 0.052, 0.043]}
        >
          <mesh
            name="Cylinder096"
            geometry={nodes.Cylinder096.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cylinder096_1"
            geometry={nodes.Cylinder096_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <mesh
          name="road"
          geometry={nodes.road.geometry}
          material={materials.road}
          position={[-8.317, -0.008, 21.345]}
          scale={[17.017, 0.076, 4.393]}
        />
        <group
          name="door"
          position={[9.74, 0.022, -4.083]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.598, -1, -0.302]}
        >
          <mesh
            name="Cube020"
            geometry={nodes.Cube020.geometry}
            material={materials.BagaPie_Window}
          />
          <mesh
            name="Cube020_1"
            geometry={nodes.Cube020_1.geometry}
            material={materials.BagaPie_Glass}
          />
          <mesh
            name="Cube020_2"
            geometry={nodes.Cube020_2.geometry}
            material={materials.BagaPie_Glass}
          />
        </group>
        <mesh
          name="wood_plank001"
          geometry={nodes.wood_plank001.geometry}
          material={materials["Wood  Material"]}
          position={[19.376, 4.021, 2.802]}
          rotation={[0, 0, -Math.PI]}
          scale={[1, 0.475, 1]}
        />
        <mesh
          name="glass_shaft_"
          geometry={nodes.glass_shaft_.geometry}
          material={materials.BagaPie_Glass}
          position={[19.376, 4.036, 4.557]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 0, 1]}
        />
        <mesh
          name="fenestration"
          geometry={nodes.fenestration.geometry}
          material={materials["Wood  Material"]}
          position={[6.549, 8.037, 10.699]}
          rotation={[-Math.PI, 1.344, Math.PI / 2]}
          scale={[-2.198, -0.107, -0.14]}
        />
        <mesh
          name="swimming_pool_border"
          geometry={nodes.swimming_pool_border.geometry}
          material={materials.dark}
          position={[-6.296, 0, 6.587]}
          scale={[4.505, 2.002, 5.067]}
        />
        <mesh
          name="base002"
          geometry={nodes.base002.geometry}
          material={materials["Hunton  BLACK oak.001"]}
          position={[-4.077, -0.029, -8.35]}
          scale={[1, 0.075, 6.51]}
        />
        <mesh
          name="wood_plank"
          geometry={nodes.wood_plank.geometry}
          material={materials["Wood  Material"]}
          position={[-3.97, -0.029, -1.978]}
          scale={[1.073, 0.127, 0.138]}
        />
        <mesh
          name="wood_plank002"
          geometry={nodes.wood_plank002.geometry}
          material={materials["Wood  Material"]}
          position={[-2.744, -0.029, -2.855]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.997, 0.127, 0.138]}
        />
        <mesh
          name="wood_plank003"
          geometry={nodes.wood_plank003.geometry}
          material={materials["Wood  Material"]}
          position={[10.161, -0.029, 12.4]}
          scale={[1.716, 0.127, 0.138]}
        />
        <mesh
          name="wood_plank004"
          geometry={nodes.wood_plank004.geometry}
          material={materials["Wood  Material"]}
          position={[12.041, -0.029, 10.836]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.779, 0.127, 0.138]}
        />
        <mesh
          name="swimming_pool"
          geometry={nodes.swimming_pool.geometry}
          material={materials["Material.001"]}
          position={[-6.296, -0.766, 6.587]}
          scale={[0.721, 0.243, 0.424]}
        />
      </group>
    </group>
  );
});

useGLTF.preload("/models/CoreServicesModel.glb");
export default CoreServicesModel;
